//
// Created by Ha on 5/5/2017.
//

#ifndef COMPORGPROJECT_SHADOW_TO_PIPELINE_H
#define COMPORGPROJECT_SHADOW_TO_PIPELINE_H

void Shadow_to_Pipeline();


#endif //COMPORGPROJECT_SHADOW_TO_PIPELINE_H
